[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self' cdn.jsdelivr.net code.jquery.com; style-src 'self' cdn.jsdelivr.net cdnjs.cloudflare.com 'unsafe-inline'; font-src 'self' cdn.jsdelivr.net; script-src 'self' code.jquery.com 'unsafe-inline'"
        X-Frame-Options = "DENY"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"