[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self' cdn.jsdelivr.net code.jquery.com; style-src 'self' cdn.jsdelivr.net cdnjs.cloudflare.com; font-src 'self' cdn.jsdelivr.net; script-src 'self' code.jquery.com www.google.com gstatic.com"
        X-Frame-Options = "DENY"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"

[[headers]]
    for = "*.js"
    [headers.values]
        Cache-Control = "public, max-age=31536000"
        Vary = "Accept-Encoding"

[[headers]]
    for = "*.css"
    [headers.values]
        Cache-Control = "public, max-age=31536000"
        Vary = "Accept-Encoding"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.otf"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.ico"
    [headers.values]
    Cache-Control = "public, max-age=31536000"


[[headers]]
  for = "*.png"
    [headers.values]
    Cache-Control = "public, max-age=2419200, must-revalidate, stale-while-revalidate=86400"


[[headers]]
  for = "*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=2419200, must-revalidate, stale-while-revalidate=86400"

[[headers]]
  for = "*.jpeg"
    [headers.values]
    Cache-Control = "public, max-age=2419200, must-revalidate, stale-while-revalidate=86400"

[[headers]]
  for = "*.svg"
    [headers.values]
    Cache-Control = "public, max-age=2419200, must-revalidate, stale-while-revalidate=86400"